This is where I enter set up the data entry for my coffee. There are improvements that could be made, but for now, it gets the job done.

In [1]:
import numpy as np
import pandas as pd

I ask for inputs that then get placed into a dataframe before concatenating the new data to my existing csv. There should be more if else statements if this was going into a production but for my own personal use, I believe it is in an acceptable state.

In [46]:
# Get the coffee info from that day

dummy_df = pd.DataFrame()

coffee_yn = input("Did you have coffee today? ")

coffee_yn = coffee_yn.lower()
if coffee_yn == 'y' or coffee_yn == 'yes':
    date_input = input('Enter the date: ')
    brand_input = input('Enter the brand of coffee used: ')
    roast_input = input('Enter the roast: ')
    blend_input = input('Enter the blend name: ')
    ice_input = input('Was the coffee made over ice? ')
    grind_input = input('What grind size was used? ')
    method_input = input('What method was used to brew? ')
    coffee_input = input('How much coffee in grams was used? ')
    water_input = input('How much water was used to brew? ')
    ice_amount = input('How much ice was used? ')
    bloom_input = input('How long was the coffee allowed to bloom? ')
    rating_input = input('What was the overall rating of the coffee? ')
    new_row = {'Date': date_input, 'Brand': brand_input, 'Roast':roast_input, 
               'Blend': blend_input, 'Iced': ice_input,
              'Grind_size': grind_input, 'Method': method_input, 'Amount_coffee': coffee_input,
               'Amount_water': water_input, 'Amount_ice': ice_amount, 'Bloom_time': bloom_input, 
               'Rating': rating_input}

    #dummy_df = dummy_df.append(new_row, ignore_index = True)
    new_row = pd.DataFrame([new_row])
    dummy_df = pd.concat([dummy_df,new_row], ignore_index = True)

else:
    print('Have a good day')

Below is the dummy df that contains how today's coffee was made.

In [47]:
#Ensuring that the info got put into the df
dummy_df

,Date,Brand,Roast,Blend,Iced,Grind_size,Method,Amount_coffee,Amount_water,Amount_ice,Bloom_time,Rating
0,01/16/2023,legrand coffee house,medium,columbia,no,6,aeropress,22,254,n/a,0,8.25

In [48]:
#df = pd.DataFrame(columns = ['Date', 'Brand', 'Roast', 'Blend', 'Iced',
#                         'Grind_size', 'Method', 'Amount_coffee', 
#                        'Amount_water', 'Amount_ice', 'Bloom_time', 
#                             'Rating'])

In [49]:
#print(df)

In [50]:
#df = pd.concat([df, dummy_df], ignore_index = True)

In [51]:
#df.to_csv('coffee.csv')

In [52]:
# Reading in the master df
coffee_df = pd.read_csv('coffee.csv', index_col = 0)
coffee_df.tail(10)

,Date,Brand,Roast,Blend,Iced,Grind_size,Method,Amount_coffee,Amount_water,Amount_ice,Bloom_time,Rating
197,01/08/2022,legrand coffee house,medium,costa rica,no,11,chemex,35,555,NaN,50,8.50
198,01/09/2022,legrand coffee house,medium,costa rica,no,11,chemex,30,504,NaN,45,7.25
199,01/11/2023,legrand coffee house,medium,columbia,no,11,chemex,35,556,NaN,45,8.00
200,01/12/2022,legrand coffee house,medium,columbia,no,11,chemex,35,557,NaN,45,8.00
201,01/12/2022,legrand coffee house,medium,columbia,no,11,chemex,30,504,NaN,45,7.50
202,01/13/2023,legrand coffee house,medium,columbia,no,11,chemex,35,558,NaN,45,7.25
203,01/17/2023,legrand coffee house,medium,columbia,no,6,chemex,39,557,NaN,45,6.00
204,01/14/2023,legrand coffee house,medium,columbia,no,11,chemex,35,554,NaN,45,8.00
205,01/15/2023,legrand coffee house,medium,columbia,no,11,chemex,35,555,NaN,45,8.00
206,01/16/2023,legrand coffee house,medium,columbia,no,11,chemex,35,557,NaN,45,8.00

Reading in the master csv that contains how I made my coffee from when I started this journey.

In [53]:
#df_1 = coffee_df[coffee_df['Brand'] == 'Red Rooster']
#print(df_1)

Below is where I concatinate my temporary dataframe with the master dataframe.

In [54]:
# Joining the day into the master
df = pd.concat([coffee_df, dummy_df], ignore_index = True)
df.tail(10)

,Date,Brand,Roast,Blend,Iced,Grind_size,Method,Amount_coffee,Amount_water,Amount_ice,Bloom_time,Rating
198,01/09/2022,legrand coffee house,medium,costa rica,no,11,chemex,30,504,NaN,45,7.25
199,01/11/2023,legrand coffee house,medium,columbia,no,11,chemex,35,556,NaN,45,8.0
200,01/12/2022,legrand coffee house,medium,columbia,no,11,chemex,35,557,NaN,45,8.0
201,01/12/2022,legrand coffee house,medium,columbia,no,11,chemex,30,504,NaN,45,7.5
202,01/13/2023,legrand coffee house,medium,columbia,no,11,chemex,35,558,NaN,45,7.25
203,01/17/2023,legrand coffee house,medium,columbia,no,6,chemex,39,557,NaN,45,6.0
204,01/14/2023,legrand coffee house,medium,columbia,no,11,chemex,35,554,NaN,45,8.0
205,01/15/2023,legrand coffee house,medium,columbia,no,11,chemex,35,555,NaN,45,8.0
206,01/16/2023,legrand coffee house,medium,columbia,no,11,chemex,35,557,NaN,45,8.0
207,01/16/2023,legrand coffee house,medium,columbia,no,6,aeropress,22,254,n/a,0,8.25

In [55]:
#df.drop(df.columns[[0]], axis = 1, inplace=True)
#df

Since this csv is still a manageable size, I save my concatinated dataframe to access again whenever I make myself coffee.

In [56]:
# New Master dataframe
df.to_csv('coffee.csv')