This is where I enter set up the data entry for my coffee. There are improvements that could be made, but for now, it gets the job done.

In [1]:
import numpy as np
import pandas as pd

I ask for inputs that then get placed into a dataframe before concatenating the new data to my existing csv. There should be more if else statements if this was going into a production but for my own personal use, I believe it is in an acceptable state.

In [2]:
# Get the coffee info from that day

dummy_df = pd.DataFrame()

coffee_yn = input("Did you have coffee today? ")

coffee_yn = coffee_yn.lower()
if coffee_yn == 'y' or coffee_yn == 'yes':
    date_input = input('Enter the date: ')
    brand_input = input('Enter the brand of coffee used: ')
    roast_input = input('Enter the roast: ')
    blend_input = input('Enter the blend name: ')
    ice_input = input('Was the coffee made over ice? ')
    grind_input = input('What grind size was used? ')
    method_input = input('What method was used to brew? ')
    coffee_input = input('How much coffee in grams was used? ')
    water_input = input('How much water was used to brew? ')
    ice_amount = input('How much ice was used? ')
    bloom_input = input('How long was the coffee allowed to bloom? ')
    grinder_used = input('Which grinder was used?')
    total_time_minutes = input('How many minutes to fully brew coffee?')
    total_time_seconds = input('How many seconds to fully  brew coffee?')
    rating_input = input('What was the overall rating of the coffee? ')
    new_row = {'Date': date_input, 'Brand': brand_input, 'Roast':roast_input, 
               'Blend': blend_input, 'Iced': ice_input,
              'Grind_size': grind_input, 'Method': method_input, 'Amount_coffee': coffee_input,
               'Amount_water': water_input, 'Amount_ice': ice_amount, 'Bloom_time': bloom_input, 
               'Grinder_used': grinder_used, 'Total_time_m': total_time_minutes, 'Total_time_s':total_time_seconds, 'Rating': rating_input}

    #dummy_df = dummy_df.append(new_row, ignore_index = True)
    new_row = pd.DataFrame([new_row])
    dummy_df = pd.concat([dummy_df,new_row], ignore_index = True)

else:
    print('Have a good day')

Below is the dummy df that contains how today's coffee was made.

In [3]:
#Ensuring that the info got put into the df
dummy_df

,Date,Brand,Roast,Blend,Iced,Grind_size,Method,Amount_coffee,Amount_water,Amount_ice,Bloom_time,Grinder_used,Total_time_m,Total_time_s,Rating
0,04/06/2023,bason,medium,Papau New Guinea,no,20,chemex,35,559,n/a,45,Wilfa,7,4,8.75

In [4]:
#df = pd.DataFrame(columns = ['Date', 'Brand', 'Roast', 'Blend', 'Iced',
#                         'Grind_size', 'Method', 'Amount_coffee', 
#                        'Amount_water', 'Amount_ice', 'Bloom_time', 
#                             'Rating'])

In [5]:
#print(df)

In [6]:
#df = pd.concat([df, dummy_df], ignore_index = True)

In [7]:
#df.to_csv('coffee.csv')

In [4]:
# Reading in the master df
coffee_df = pd.read_csv('coffee.csv', index_col = 0)
coffee_df.tail(10)

,Date,Brand,Roast,Blend,Iced,Grind_size,Method,Amount_coffee,Amount_water,Amount_ice,Bloom_time,Rating
248,03/20/2023,bason,unknown,ironman blend,no,11,chemex,35,554,NaN,45,5.00
249,03/20/2023,bason,unknown,ironman blend,no,6,aeropress,22,230,NaN,0,8.50
250,03/21/2023,bason,unknown,ironman blend,no,11,chemex,35,551,NaN,45,8.00
251,03/24/2023,bason,dark,guatemalan huehuetenango,no,5,aeropress,22,242,NaN,0,8.25
252,03/25/2023,bason,unknown,ironman blend,no,12,chemex,38,605,NaN,45,7.00
253,03/28/2023,bason,unknown,ironman blend,no,12,chemex,35,575,NaN,50,7.75
254,03/27/2023,bason,unknown,ironman blend,no,12,chemex,35,551,NaN,45,8.00
255,03/30/2023,bason,unknown,ironman blend,no,12,chemex,35,554,NaN,45,8.25
256,03/30/2023,bason,dark,guatemalan huehuetenango,no,5,aeropresss,22,241,NaN,0,8.25
257,04/05/2023,bason,medium,Papua New Guinea,no,12,chemex,35,553,NaN,45,8.50

Reading in the master csv that contains how I made my coffee from when I started this journey.

In [9]:
#df_1 = coffee_df[coffee_df['Brand'] == 'Red Rooster']
#print(df_1)

Below is where I concatinate my temporary dataframe with the master dataframe.

In [5]:
# Joining the day into the master
df = pd.concat([coffee_df, dummy_df], ignore_index = True)
df.tail(10)

,Date,Brand,Roast,Blend,Iced,Grind_size,Method,Amount_coffee,Amount_water,Amount_ice,Bloom_time,Rating,Grinder_used,Total_time_m,Total_time_s
249,03/20/2023,bason,unknown,ironman blend,no,6,aeropress,22,230,NaN,0,8.5,NaN,NaN,NaN
250,03/21/2023,bason,unknown,ironman blend,no,11,chemex,35,551,NaN,45,8.0,NaN,NaN,NaN
251,03/24/2023,bason,dark,guatemalan huehuetenango,no,5,aeropress,22,242,NaN,0,8.25,NaN,NaN,NaN
252,03/25/2023,bason,unknown,ironman blend,no,12,chemex,38,605,NaN,45,7.0,NaN,NaN,NaN
253,03/28/2023,bason,unknown,ironman blend,no,12,chemex,35,575,NaN,50,7.75,NaN,NaN,NaN
254,03/27/2023,bason,unknown,ironman blend,no,12,chemex,35,551,NaN,45,8.0,NaN,NaN,NaN
255,03/30/2023,bason,unknown,ironman blend,no,12,chemex,35,554,NaN,45,8.25,NaN,NaN,NaN
256,03/30/2023,bason,dark,guatemalan huehuetenango,no,5,aeropresss,22,241,NaN,0,8.25,NaN,NaN,NaN
257,04/05/2023,bason,medium,Papua New Guinea,no,12,chemex,35,553,NaN,45,8.5,NaN,NaN,NaN
258,04/06/2023,bason,medium,Papau New Guinea,no,20,chemex,35,559,n/a,45,8.75,Wilfa,7,4

In [11]:
#df.drop(df.columns[[0]], axis = 1, inplace=True)
#df

Since this csv is still a manageable size, I save my concatinated dataframe to access again whenever I make myself coffee.

In [ ]:
# New Master dataframe
df.to_csv('coffee.csv')